const img = (id) => `https://images.unsplash.com/${id}?w=500&auto=format&fit=crop&q=80`;

export const CATEGORIES = [
  "Semua",
  "Sembako",
  "Kelontong",
  "Perawatan Diri",
  "Bumbu",
  "Sayuran",
  "Protein",
];

export const PRODUCTS = [
  // ─── SEMBAKO & BERAS ───────────────────────────────────────────
  {
    id: "beras-5kg",
    name: "Beras Premium Setra Ramos 5kg",
    category: "Sembako",
    price: 72500,
    old_price: 77000,
    unit: "sak",
    stock: 350,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: img("photo-1586201375761-83865001e31c"),
    desc: "Beras putih pilihan kualitas premium, pulen, bersih dari batu dan kutu. Komoditas pokok utama jaringan Koperasi Merah Putih Depok.",
    nutrition: { kalori: 360, protein: 6.6, karbo: 78.9, lemak: 0.6 },
  },
  {
    id: "beras",
    name: "Beras Pulen Super Sukmajaya 1kg",
    category: "Sembako",
    price: 15000,
    old_price: 16500,
    unit: "kg",
    stock: 500,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: img("photo-1536304993881-ff6e9eefa2a6"),
    desc: "Beras kiloan mutu terjamin, putih alami tanpa pemutih buatan, nasi pulen dan wangi tahan lama.",
    nutrition: { kalori: 360, protein: 6.6, karbo: 78.9, lemak: 0.6 },
  },
  {
    id: "mentega-blueband",
    name: "Mentega Margarin Blue Band Serbaguna 200g",
    category: "Sembako",
    price: 11500,
    old_price: 13000,
    unit: "sachet",
    stock: 250,
    origin: "Gudang Pusat Sukmajaya",
    img: img("photo-1589985270826-4b7bb135bc9d"),
    desc: "Margarin serbaguna gurih dan bernutrisi, diperkaya vitamin A, B1, B2, D, E. Cocok untuk olesan roti, menumis, dan membuat kue.",
    nutrition: { kalori: 717, protein: 0.2, karbo: 0.4, lemak: 81 },
  },
  {
    id: "mentega-butter",
    name: "Mentega Butter Segar Golden Churn 227g",
    category: "Sembako",
    price: 38000,
    old_price: 42000,
    unit: "kaleng",
    stock: 60,
    origin: "Gudang Pusat Sukmajaya",
    img: img("photo-1627308595229-7830a5c91f9f"),
    desc: "Mentega butter kualitas premium dengan aroma wangi mentega asli, gurih untuk masakan dan panggangan kue keluarga.",
    nutrition: { kalori: 717, protein: 0.8, karbo: 0.1, lemak: 81 },
  },
  {
    id: "minyak",
    name: "Minyak Goreng Sawit Pilihan 2 Liter",
    category: "Sembako",
    price: 34000,
    old_price: 37000,
    unit: "pouch",
    stock: 260,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: img("photo-1474979266404-7eaacbcd87c5"),
    desc: "Minyak goreng kelapa sawit bening, titik didih stabil, membuat gorengan renyah dan gurih tahan lama.",
    nutrition: { kalori: 884, protein: 0, karbo: 0, lemak: 100 },
  },
  {
    id: "gula",
    name: "Gula Pasir Kristal Putih 1kg",
    category: "Sembako",
    price: 17500,
    old_price: 18500,
    unit: "kg",
    stock: 200,
    origin: "Gudang Pusat Sukmajaya",
    img: img("photo-1581795669223-09203b83bf61"),
    desc: "Gula pasir kristal putih dari tebu pilihan, manis alami untuk teh, kopi, dan aneka resep dapur.",
    nutrition: { kalori: 394, protein: 0, karbo: 100, lemak: 0 },
  },
  {
    id: "tepung",
    name: "Tepung Terigu Segitiga Biru 1kg",
    category: "Sembako",
    price: 12500,
    old_price: 14000,
    unit: "kg",
    stock: 180,
    origin: "Distributor Sembako Sukmajaya",
    img: img("photo-1509440159596-0249088772ff"),
    desc: "Tepung terigu protein sedang serbaguna untuk aneka gorengan, kue, martabak, dan camilan keluarga.",
    nutrition: { kalori: 365, protein: 10.3, karbo: 76.3, lemak: 1.2 },
  },
  {
    id: "susu-kental-manis",
    name: "Susu Kental Manis Frisian Flag Gold 370g",
    category: "Sembako",
    price: 13500,
    old_price: 15000,
    unit: "kaleng",
    stock: 190,
    origin: "Gudang Pusat Sukmajaya",
    img: img("photo-1550583724-b2692b85b150"),
    desc: "Susu kental manis kaya rasa susu lezat dan gurih, tinggi kalsium dan vitamin untuk sarapan roti dan kopi.",
    nutrition: { kalori: 130, protein: 3, karbo: 22, lemak: 3.5 },
  },

  // ─── WARUNG KELONTONG & KEBUTUHAN RUMAH TANGGA ───────────────────
  {
    id: "mie-indomie",
    name: "Mie Instan Indomie Goreng Spesial (Isi 5 Pcs)",
    category: "Kelontong",
    price: 16000,
    old_price: 17500,
    unit: "paket",
    stock: 400,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: img("photo-1612927601601-6638404737ce"),
    desc: "Mie goreng instan favorit Indonesia rasa gurih nikmat dengan taburan bawang goreng renyah. Kebutuhan pokok warung kelontong.",
    nutrition: { kalori: 380, protein: 8, karbo: 54, lemak: 14 },
  },
  {
    id: "kopi-kapal-api",
    name: "Kopi Kapal Api Spesial Mix (Renceng 10 Sachet)",
    category: "Kelontong",
    price: 14000,
    old_price: 16000,
    unit: "renceng",
    stock: 210,
    origin: "Pos Cabang Beji, Depok",
    img: img("photo-1559056199-641a0ac8b55e"),
    desc: "Paduan biji kopi pilihan dengan gula murni beraroma mantap. Praktis diseduh untuk semangat setiap hari.",
    nutrition: { kalori: 110, protein: 1, karbo: 23, lemak: 1.5 },
  },
  {
    id: "teh-sariwangi",
    name: "Teh Celup Sariwangi Asli Kotak (Isi 25 Bags)",
    category: "Kelontong",
    price: 7500,
    old_price: 9000,
    unit: "kotak",
    stock: 180,
    origin: "Distributor Sembako Sukmajaya",
    img: img("photo-1576092768241-dec231879fc3"),
    desc: "Teh hitam celup aroma khas nusantara, hangat dan menyegarkan suasana kumpul bersama keluarga.",
    nutrition: { kalori: 2, protein: 0, karbo: 0.5, lemak: 0 },
  },
  {
    id: "sabun-cuci-piring",
    name: "Sabun Cuci Piring Sunlight Jeruk Nipis 750ml",
    category: "Kelontong",
    price: 15000,
    old_price: 17000,
    unit: "pouch",
    stock: 220,
    origin: "Gudang Pusat Sukmajaya",
    img: img("photo-1585421514738-01798e348b17"),
    desc: "Cairan pencuci piring konsentrat ekstrak jeruk nipis asli, ampuh angkat lemak membandel 5x lebih cepat.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "deterjen-rinso",
    name: "Deterjen Bubuk Rinso Anti Noda + Molto 770g",
    category: "Kelontong",
    price: 21500,
    old_price: 24500,
    unit: "pack",
    stock: 180,
    origin: "Distributor Kelontong Depok",
    img: img("photo-1582735689369-4fe89db7114c"),
    desc: "Deterjen bubuk formula konsentrat membersihkan noda membandel dalam 1x kucek dan wangi tahan hingga 21 hari.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },

  // ─── PERAWATAN DIRI & MANDI ──────────────────────────────────────
  {
    id: "shampo-lifebuoy",
    name: "Shampo Rambut Lifebuoy Anti Dandruff 170ml",
    category: "Perawatan Diri",
    price: 19500,
    old_price: 22000,
    unit: "botol",
    stock: 120,
    origin: "Sentra Kelontong Sukmajaya",
    img: img("photo-1535585209827-a15fcdbc4c2d"),
    desc: "Shampo pembersih rambut keluarga, menyegarkan kulit kepala, bebas ketombe dan rambut harum sepanjang hari.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "shampo-pantene",
    name: "Shampo Pantene Total Damage Care 160ml",
    category: "Perawatan Diri",
    price: 24000,
    old_price: 27000,
    unit: "botol",
    stock: 90,
    origin: "Distributor Sukmajaya Depok",
    img: img("photo-1522337360788-8b13dee7a37e"),
    desc: "Shampo perawatan rambut halus dan berkilau, melindungi dari kerusakan rambut akibat polusi dan panas.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "sabun-mandi",
    name: "Sabun Mandi Batang Dettol Original (Isi 3)",
    category: "Perawatan Diri",
    price: 17500,
    old_price: 20000,
    unit: "pack",
    stock: 140,
    origin: "Sentra Kelontong Sukmajaya",
    img: img("photo-1607006314180-348e3671239c"),
    desc: "Sabun antibakteri pelindung kuman keluarga sehari-hari dengan kesegaran alami pinus tahan lama.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "pasta-gigi",
    name: "Pasta Gigi Pepsodent Pencegah Gigi Berlubang 190g",
    category: "Perawatan Diri",
    price: 15500,
    old_price: 18000,
    unit: "tube",
    stock: 160,
    origin: "Distributor Sembako Sukmajaya",
    img: img("photo-1559599101-f09722fb4948"),
    desc: "Pasta gigi perlindungan mikro kalsium aktif dan pro-fluoride ganda untuk menjaga kekuatan dan kebersihan gigi keluarga.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },

  // ─── BUMBU DAPUR ─────────────────────────────────────────────────
  {
    id: "kecap-bango",
    name: "Kecap Manis Bango Botol 520ml",
    category: "Bumbu",
    price: 24500,
    old_price: 27000,
    unit: "botol",
    stock: 130,
    origin: "Distributor Sembako Sukmajaya",
    img: img("photo-1472476443507-c7a5948772fc"),
    desc: "Kecap manis terbuat dari 4 bahan alami pilihan dengan kedelai hitam mallika berkualitas tinggi, kental hitam alami meresap sempurna.",
    nutrition: { kalori: 60, protein: 1, karbo: 14, lemak: 0 },
  },
  {
    id: "garam-dapur",
    name: "Garam Dapur Beryodium Cap Kapal Layar 250g",
    category: "Bumbu",
    price: 4000,
    old_price: 5000,
    unit: "bks",
    stock: 300,
    origin: "Pos Cabang Beji, Depok",
    img: img("photo-1626078571935-0eaa4f40c64a"),
    desc: "Garam konsumsi beryodium halus, higienis, penyedap rasa alami masakan keluarga sehari-hari.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "cabai-merah",
    name: "Cabai Merah Keriting Segar 1kg",
    category: "Bumbu",
    price: 32000,
    old_price: 38000,
    unit: "kg",
    stock: 60,
    origin: "Petani Sawangan Depok",
    img: img("photo-1592137403099-624c888e3f4d"),
    desc: "Cabai merah keriting segar, warna merah merata, pedas pas. Bumbu wajib untuk sambal dan tumisan.",
    nutrition: { kalori: 40, protein: 1.9, karbo: 8.8, lemak: 0.4 },
  },
  {
    id: "cabai-rawit",
    name: "Cabai Rawit Merah Pedas 1kg",
    category: "Bumbu",
    price: 38000,
    old_price: 42000,
    unit: "kg",
    stock: 45,
    origin: "Petani Sawangan Depok",
    img: img("photo-1587131787055-e62b21a7752a"),
    desc: "Cabai rawit merah pedas pilihan. Segar dipetik, cocok untuk sambal ulek dan lalapan.",
    nutrition: { kalori: 40, protein: 2.4, karbo: 7.5, lemak: 0.6 },
  },
  {
    id: "bawang-merah",
    name: "Bawang Merah Brebes Pilihan 1kg",
    category: "Bumbu",
    price: 30000,
    old_price: 34000,
    unit: "kg",
    stock: 120,
    origin: "Sentra Bumbu Pasar Kemiri Depok",
    img: img("photo-1508747703725-719777637510"),
    desc: "Bawang merah umbi padat, kering dan wangi kuat untuk menumis aneka masakan nusantara.",
    nutrition: { kalori: 40, protein: 1.5, karbo: 9.3, lemak: 0.2 },
  },
  {
    id: "bawang-putih",
    name: "Bawang Putih Kating Super 1kg",
    category: "Bumbu",
    price: 28000,
    old_price: 32000,
    unit: "kg",
    stock: 100,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: img("photo-1540151812223-b30b3fab58e6"),
    desc: "Bawang putih kating, siung besar dan kering. Bumbu dasar masakan sehari-hari keluarga.",
    nutrition: { kalori: 149, protein: 6.4, karbo: 33.1, lemak: 0.5 },
  },

  // ─── SAYURAN SEGAR ───────────────────────────────────────────────
  {
    id: "kentang",
    name: "Kentang Granola Dieng 1kg",
    category: "Sayuran",
    price: 14000,
    old_price: 16000,
    unit: "kg",
    stock: 200,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: img("photo-1518977676601-b53f82aba655"),
    desc: "Kentang granola padat dan tidak bertunas. Cocok untuk direbus, digoreng, perkedel atau sop sayur.",
    nutrition: { kalori: 77, protein: 2.0, karbo: 17.5, lemak: 0.1 },
  },
  {
    id: "tomat",
    name: "Tomat Merah Segar 1kg",
    category: "Sayuran",
    price: 10000,
    old_price: 12000,
    unit: "kg",
    stock: 80,
    origin: "Petani Sukmajaya Depok",
    img: img("photo-1546094096-0df4bcaaa337"),
    desc: "Tomat merah segar, berair dan manis alami. Cocok untuk jus buah, sambal tomat, dan sayur sop.",
    nutrition: { kalori: 18, protein: 0.9, karbo: 3.9, lemak: 0.2 },
  },
  {
    id: "wortel",
    name: "Wortel Segar Manis 1kg",
    category: "Sayuran",
    price: 12000,
    old_price: 14000,
    unit: "kg",
    stock: 75,
    origin: "Petani Sukmajaya Depok",
    img: img("photo-1447175008436-054170c2e979"),
    desc: "Wortel segar renyah kaya vitamin A, siap untuk sayur sop bening, capcay, dan jus.",
    nutrition: { kalori: 41, protein: 0.9, karbo: 9.6, lemak: 0.2 },
  },
  {
    id: "bayam",
    name: "Bayam Hijau Segar 1 Ikat",
    category: "Sayuran",
    price: 5000,
    old_price: 6000,
    unit: "ikat",
    stock: 70,
    origin: "Kebun Warga Sukmajaya",
    img: img("photo-1576045057995-568f588f82fb"),
    desc: "Bayam hijau segar daun muda bersih, kaya zat besi untuk sayur bening keluarga.",
    nutrition: { kalori: 23, protein: 2.9, karbo: 3.6, lemak: 0.4 },
  },
  {
    id: "kangkung",
    name: "Kangkung Segar Daun Lebar 1 Ikat",
    category: "Sayuran",
    price: 4000,
    old_price: 5000,
    unit: "ikat",
    stock: 85,
    origin: "Kebun Warga Sukmajaya",
    img: img("photo-1563245372-f21724e3856d"),
    desc: "Kangkung segar batang renyah, nikmat untuk tumis kangkung terasi dan plecing.",
    nutrition: { kalori: 19, protein: 3.0, karbo: 3.1, lemak: 0.3 },
  },

  // ─── PROTEIN & LAUK PAUK ─────────────────────────────────────────
  {
    id: "telur",
    name: "Telur Ayam Negeri Segar 1kg",
    category: "Protein",
    price: 27500,
    old_price: 29500,
    unit: "kg",
    stock: 150,
    origin: "Peternak Sawangan Depok",
    img: img("photo-1582722872445-44dc5f7e3c8f"),
    desc: "Telur ayam negeri segar, cangkang bersih, kuning telur pekat. Sumber protein harian utama keluarga.",
    nutrition: { kalori: 143, protein: 12.6, karbo: 0.7, lemak: 9.5 },
  },
  {
    id: "ayam",
    name: "Ayam Potong Segar Utuh 1 Ekor",
    category: "Protein",
    price: 35000,
    old_price: 38000,
    unit: "ekor",
    stock: 55,
    origin: "RPH Sukmajaya Depok",
    img: img("photo-1604503468506-a8da13d82791"),
    desc: "Ayam potong segar dipotong higienis, daging empuk dan gurih untuk aneka olahan sup, goreng, atau bakar.",
    nutrition: { kalori: 217, protein: 25, karbo: 0, lemak: 12 },
  },
  {
    id: "daging-sapi",
    name: "Daging Sapi Segar Khas Depok 1kg",
    category: "Protein",
    price: 135000,
    old_price: 140000,
    unit: "kg",
    stock: 25,
    origin: "RPH Sukmajaya Depok",
    img: img("photo-1551024709-8f23befc6f87"),
    desc: "Daging sapi segar merah cerah tanpa lemak berlebih. Cocok untuk semur, rendang, dan sop buntut.",
    nutrition: { kalori: 250, protein: 26, karbo: 0, lemak: 15 },
  },
  {
    id: "tahu",
    name: "Tahu Putih Lembut Segar 1 Bungkus",
    category: "Protein",
    price: 10000,
    old_price: 12000,
    unit: "bungkus",
    stock: 65,
    origin: "Sentra Tahu Tempe Sukmajaya",
    img: img("photo-1546069901-d5bfd2cbfb2c"),
    desc: "Tahu putih lembut gurih dari kedelai murni pilihan tanpa bahan pengawet.",
    nutrition: { kalori: 80, protein: 8.0, karbo: 1.9, lemak: 4.5 },
  },
  {
    id: "tempe",
    name: "Tempe Kedelai Murni Daun Pisang 1 Papan",
    category: "Protein",
    price: 8000,
    old_price: 9500,
    unit: "papan",
    stock: 70,
    origin: "Sentra Tahu Tempe Sukmajaya",
    img: img("photo-1601050690597-df0568f70950"),
    desc: "Tempe kedelai segar dibungkus daun, padat kedelai dan higienis kaya protein nabati.",
    nutrition: { kalori: 193, protein: 20.8, karbo: 7.6, lemak: 10.9 },
  },
];

export function formatRp(n) {
  return "Rp " + (n || 0).toLocaleString("id-ID");
}
