const localImg = (fileName) => encodeURI(`/images/${fileName}`);

export const CATEGORIES = [
  "Semua",
  "Sembako",
  "Kelontong",
  "Perawatan Diri",
  "Bumbu",
  "Sayuran",
  "Protein",
];

export const PRODUCTS = [
  // ─── SEMBAKO & MINYAK ───────────────────────────────────────────
  {
    id: "sania-pouch-2l",
    name: "Sania Minyak Goreng Pouch 2 Liter",
    category: "Sembako",
    price: 37000,
    old_price: 40000,
    unit: "pouch",
    stock: 320,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Sania Minyak Goreng Pouch.png"),
    desc: "Minyak goreng kelapa sawit premium diproduksi dari kelapa sawit pilihan dengan fortifikasi vitamin E & provitamin A.",
    nutrition: { kalori: 884, protein: 0, karbo: 0, lemak: 100 },
  },
  {
    id: "sari-roti-jumbo",
    name: "Sari Roti Tawar Kupas Jumbo",
    category: "Sembako",
    price: 17500,
    old_price: 19500,
    unit: "pack",
    stock: 150,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Sari Roti Tawar Kupas Jumbo.jpg"),
    desc: "Roti tawar kupas lembut higienis kemasan jumbo isi lebih banyak, pas untuk sarapan keluarga dengan selai atau margarin.",
    nutrition: { kalori: 140, protein: 4, karbo: 26, lemak: 1.5 },
  },
  {
    id: "refill-aqua-galon",
    name: "Refill AQUA Air Mineral Galon 19 Liter",
    category: "Sembako",
    price: 22000,
    old_price: 25000,
    unit: "galon",
    stock: 200,
    origin: "Sentra Distribusi Aqua Sukmajaya",
    img: localImg("REFILL AQUA Mineral Water Galon.webp"),
    desc: "Air mineral pegunungan asli kemasan galon 19 liter teruji klinis, standar kemurnian air minum keluarga Depok.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "blueband-cup-250",
    name: "Blue Band Serbaguna Margarine Cup 250g",
    category: "Sembako",
    price: 16500,
    old_price: 18500,
    unit: "cup",
    stock: 220,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Blue Band Serbaguna Margarine Cup.jpg"),
    desc: "Margarin serbaguna dalam kemasan cup praktis, diperkaya Omega 3, 6, dan 6 vitamin untuk olesan roti dan memasak.",
    nutrition: { kalori: 717, protein: 0.2, karbo: 0.4, lemak: 81 },
  },

  // ─── BUMBU DAPUR ─────────────────────────────────────────────────
  {
    id: "bango-520",
    name: "Bango Kecap Manis Botol 520ml",
    category: "Bumbu",
    price: 24500,
    old_price: 27500,
    unit: "botol",
    stock: 240,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Bango Kecap Manis Botol.jpg"),
    desc: "Kecap manis berkualitas terbuat dari kedelai hitam pilihan Mallika, gula kelapa alami, dan garam tanpa bahan pengawet.",
    nutrition: { kalori: 60, protein: 1, karbo: 14, lemak: 0 },
  },
  {
    id: "royco-sapi-230",
    name: "Royco Bumbu Kaldu Sapi Ziplock 230g",
    category: "Bumbu",
    price: 11500,
    old_price: 13500,
    unit: "pouch",
    stock: 280,
    origin: "Distributor Bumbu Sukmajaya",
    img: localImg("Royco Bumbu Kaldu Penyedap Rasa Sapi Ziplock.png"),
    desc: "Ekstrak kaldu tulang sumsum dan daging sapi rebus lama, kemasan ziplock praktis kedap udara.",
    nutrition: { kalori: 15, protein: 0.5, karbo: 2, lemak: 0.3 },
  },
  {
    id: "totole-jamur-200",
    name: "Totole Kaldu Rasa Jamur Granule 200g",
    category: "Bumbu",
    price: 22500,
    old_price: 25500,
    unit: "pouch",
    stock: 190,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Totole Kaldu Rasa Jamur.png"),
    desc: "Bumbu kaldu vegetarian ekstrak jamur alami tanpa pengawet buatan, memberikan rasa gurih alami masakan.",
    nutrition: { kalori: 10, protein: 0.2, karbo: 2, lemak: 0 },
  },
  {
    id: "racik-ayam-goreng",
    name: "Indofood Bumbu Racik Ayam Goreng",
    category: "Bumbu",
    price: 3000,
    old_price: 3500,
    unit: "sachet",
    stock: 500,
    origin: "Pos Cabang Beji, Depok",
    img: localImg("Indofood Bumbu Racik Ayam Goreng.png"),
    desc: "Bumbu marinasi ayam goreng praktis dengan rempah asli khas Nusantara, meresap sampai ke tulang tanpa perlu bumbu tambahan.",
    nutrition: { kalori: 20, protein: 0.5, karbo: 4, lemak: 0.2 },
  },
  {
    id: "racik-sayur-asem",
    name: "Indofood Bumbu Racik Sayur Asem",
    category: "Bumbu",
    price: 3000,
    old_price: 3500,
    unit: "sachet",
    stock: 450,
    origin: "Pos Cabang Beji, Depok",
    img: localImg("Indofood Bumbu Racik Sayur Asem.png"),
    desc: "Bumbu instan kuah sayur asem segar khas Betawi/Sunda, racikan pas dan lezat untuk santapan keluarga.",
    nutrition: { kalori: 15, protein: 0.3, karbo: 3.5, lemak: 0.1 },
  },
  {
    id: "racik-tempe-goreng",
    name: "Indofood Bumbu Racik Tempe Goreng",
    category: "Bumbu",
    price: 3000,
    old_price: 3500,
    unit: "sachet",
    stock: 480,
    origin: "Pos Cabang Beji, Depok",
    img: localImg("Indofood Bumbu Racik Tempe GorengIndofood Bumbu Racik Tempe Goreng.png"),
    desc: "Bumbu racik praktis rendaman tempe dan tahu gurih asin renyah rempah alami.",
    nutrition: { kalori: 20, protein: 0.4, karbo: 4, lemak: 0.2 },
  },

  // ─── SAYURAN & PERTANIAN ─────────────────────────────────────────
  {
    id: "kentang-astro",
    name: "Kentang Segar Astro Farm 1kg",
    category: "Sayuran",
    price: 18500,
    old_price: 21000,
    unit: "kg",
    stock: 180,
    origin: "Astro Farm — Sukmajaya Fresh Hub",
    img: localImg("Kentang - Astro Farm.png"),
    desc: "Kentang segar pilihan mutu tinggi Astro Farm, kulit bersih dan umbi padat untuk perkedel, sop, dan gorengan.",
    nutrition: { kalori: 77, protein: 2.0, karbo: 17.5, lemak: 0.1 },
  },

  // ─── PROTEIN & TELUR ─────────────────────────────────────────────
  {
    id: "telur-astro-1kg",
    name: "Telur Ayam Negeri Segar Astro Farm 1kg",
    category: "Protein",
    price: 29500,
    old_price: 32500,
    unit: "kg",
    stock: 220,
    origin: "Astro Farm — Peternak Depok",
    img: localImg("Telur Ayam Negeri Astro Farm.jpg"),
    desc: "Telur ayam negeri segar pilihan Astro Farm, cangkang kokoh bersih, kuning telur omega tinggi nutrisi harian.",
    nutrition: { kalori: 143, protein: 12.6, karbo: 0.7, lemak: 9.5 },
  },

  // ─── WARUNG KELONTONG & KEBUTUHAN RUMAH TANGGA ───────────────────
  {
    id: "indomie-cabe-ijo",
    name: "Indomie Goreng Cabe Ijo Mie Instan (Isi 5 Pcs)",
    category: "Kelontong",
    price: 16500,
    old_price: 18500,
    unit: "paket",
    stock: 380,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Indomie Goreng Cabe Ijo Mie Instan.png"),
    desc: "Mie instan goreng dengan bumbu cabai hijau asli dan aroma khas rempah hijau yang menggugah selera.",
    nutrition: { kalori: 390, protein: 8, karbo: 55, lemak: 15 },
  },
  {
    id: "indomie-rendang",
    name: "Indomie Goreng Rendang Mie Instan (Isi 5 Pcs)",
    category: "Kelontong",
    price: 16500,
    old_price: 18500,
    unit: "paket",
    stock: 360,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Indomie Goreng Rendang Mie Instan.jpeg"),
    desc: "Mie instan goreng bumbu rendang autentik Minang dengan kelezatan rempah santan pekat yang khas.",
    nutrition: { kalori: 400, protein: 8, karbo: 56, lemak: 16 },
  },
  {
    id: "indomie-ayam-bawang",
    name: "Indomie Kuah Ayam Bawang Mie Instan (Isi 5 Pcs)",
    category: "Kelontong",
    price: 15500,
    old_price: 17500,
    unit: "paket",
    stock: 400,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Indomie Kuah Ayam Bawang Mie Instan.png"),
    desc: "Mie instan kuah rasa ayam bawang legendaris dengan minyak bawang gurih dan kaldu hangat menenangkan.",
    nutrition: { kalori: 350, protein: 7.5, karbo: 50, lemak: 13 },
  },
  {
    id: "indomie-ayam-spesial",
    name: "Indomie Kuah Ayam Spesial Mie Instan (Isi 5 Pcs)",
    category: "Kelontong",
    price: 15500,
    old_price: 17500,
    unit: "paket",
    stock: 390,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Indomie Kuah Ayam Spesial Mie Instan.jpeg"),
    desc: "Mie instan kuah kaldu ayam spesial gurih lembut, pas dinikmati bersama telur rebus dan cabai rawit.",
    nutrition: { kalori: 360, protein: 8, karbo: 51, lemak: 14 },
  },
  {
    id: "sedaap-goreng-isi5",
    name: "Mie Sedaap Goreng Isi 5 Pcs",
    category: "Kelontong",
    price: 15500,
    old_price: 17500,
    unit: "paket",
    stock: 350,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Mie Sedaap Goreng Isi 5 Mie Instan.jpg"),
    desc: "Mie goreng instan lezat dengan taburan kriuk bawang gurih renyah sensasi kriuk-kriuk asli.",
    nutrition: { kalori: 410, protein: 8.5, karbo: 58, lemak: 16 },
  },
  {
    id: "sunlight-nipis-750",
    name: "Sunlight Jeruk Nipis Cairan Pencuci Piring Refill 750ml",
    category: "Kelontong",
    price: 15000,
    old_price: 17500,
    unit: "pouch",
    stock: 300,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Sunlight Jeruk Nipis Cairan Pencuci Piring Refill.jpg"),
    desc: "Cairan pencuci piring ekstrak 100 jeruk nipis asli bersihkan lemak membandel dan bau amis seketika.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "bundle-rinso-molto-1500",
    name: "Bundle 2 Rinso Molto Anti Noda Rose Fresh 1500g",
    category: "Kelontong",
    price: 68000,
    old_price: 76000,
    unit: "paket",
    stock: 150,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Bundle 2 Rinso Molto Anti Noda Rose Fresh Deterjen Cair 1500 gram.jpg"),
    desc: "Paket hemat 2 pouch Rinso Molto Anti Noda Rose Fresh deterjen cair 1500g, wangi mawar tahan lama dan bersih optimal.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "rinso-kapsul-sakura",
    name: "Rinso Kapsul Matic Sakura Bloom 16 Kapsul",
    category: "Kelontong",
    price: 35000,
    old_price: 40000,
    unit: "box",
    stock: 130,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Rinso Kapsul Matic Sakura Bloom Deterjen Cair.jpg"),
    desc: "Deterjen kapsul 3-in-1 inovatif pembersih konsentrat noda, pelembut dan pewangi bunga Sakura mekar.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "rinso-matic-front-1600",
    name: "Rinso Matic Front Load Deterjen Cair 1.6L",
    category: "Kelontong",
    price: 49500,
    old_price: 56000,
    unit: "pouch",
    stock: 110,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Rinso Matic Front Load Deterjen Cair.jpg"),
    desc: "Deterjen cair mesin cuci bukaan depan formula konsentrat rendah busa menjaga keawetan mesin dan serat kain.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "bundle-molto-morning",
    name: "Bundle Isi 2 Molto Morning Fresh Pelembut Pakaian",
    category: "Kelontong",
    price: 45000,
    old_price: 52000,
    unit: "paket",
    stock: 160,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Bundle Isi 2 Molto Morning Fresh Pelembut dan Pewangi Pakaian.jpg"),
    desc: "Paket isi 2 Molto pewangi dan pelembut pakaian konsentrat dengan kesegaran aroma pagi hari sepanjang hari.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "molto-baby-720",
    name: "Molto Pure Baby Soft & Gentle Pelembut Pakaian 720ml",
    category: "Kelontong",
    price: 26000,
    old_price: 30000,
    unit: "pouch",
    stock: 140,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Molto Pure Baby Soft & Gentle Pelembut Pakaian.jpg"),
    desc: "Pelembut dan pewangi pakaian bayi teruji dermatologis, menjaga serat pakaian lembut ramah kulit sensitif.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "kispray-gold-300",
    name: "Kispray Glamorous Gold Pelicin Pakaian Refill 300ml",
    category: "Kelontong",
    price: 7500,
    old_price: 9000,
    unit: "pouch",
    stock: 220,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Kispray Glamorous Gold Pelicin Pakaian Refill.jpeg"),
    desc: "Cairan pelicin dan pewangi pakaian setrika konsentrat aroma mewah Glamorous Gold anti bau apek.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "wipol-cemara-780",
    name: "Wipol Karbol Wangi Cemara Pouch 780ml",
    category: "Kelontong",
    price: 18000,
    old_price: 21000,
    unit: "pouch",
    stock: 210,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Wipol Karbol Cemara Pembersih Lantai Pouch.jpg"),
    desc: "Karbol pembersih lantai wangi pinus cemara segar, ampuh basmi kuman 99.9% dan hilangkan bau tak sedap.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
  {
    id: "sabun-ekonomi-citrus",
    name: "Sabun Colek Krim Ekonomi Fresh Citrus 380g",
    category: "Kelontong",
    price: 5500,
    old_price: 6500,
    unit: "pot",
    stock: 350,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Ekonomi Fresh Citrus Sabun Colek Krim.jpg"),
    desc: "Sabun colek krim multiguna aroma jeruk segar, membersihkan noda minyak piring dan cucian secara ekonomis.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },

  // ─── PERAWATAN DIRI ──────────────────────────────────────────────
  {
    id: "tissue-nice-bogo",
    name: "Buy 1 Get 1 Nice Living Facial Tissue Soft Pack 400+100",
    category: "Perawatan Diri",
    price: 28500,
    old_price: 34000,
    unit: "paket",
    stock: 250,
    origin: "Gudang Induk Sukmajaya, Depok",
    img: localImg("Buy 1 Get 1 Nice Living Facial Tissue Soft Pack 400+100.jpg"),
    desc: "Promo beli 1 gratis 1 tisu wajah Nice 400+100 lembar 2 ply, lembut dan higienis untuk kebutuhan keluarga.",
    nutrition: { kalori: 0, protein: 0, karbo: 0, lemak: 0 },
  },
];

export function formatRp(n) {
  return "Rp " + (n || 0).toLocaleString("id-ID");
}
